### ISSUE TITLE
HTTPParser error

### ISSUE THREAD

**Issue by flyish** [NetEase/pomelo#1006]
Caught exception: TypeError: ParserIncomingMessage is not a constructor
    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
    at socketOnData (_http_server.js:472:20)
    at Socket.emit (events.js:180:13)
    at Processor.add (F:\work\pomelo\HelloWorld\game-server\node_modules\pomelo\lib\connectors\hybrid\wsprocessor.js:41:12)
    at processHttp (F:\work\pomelo\HelloWorld\game-server\node_modules\pomelo\lib\connectors\hybrid\switcher.js:98:13)
    at Socket.<anonymous> (F:\work\pomelo\HelloWorld\game-server\node_modules\pomelo\lib\connectors\hybrid\switcher.js:65:7)

**Comment by chenzeZzz** [comment]
怎么解决的？

**Comment by chenzeZzz** [comment]
@flyish 
怎么解决的

**Comment by flyish** [comment]
@chenzeZzz 没有解决掉，没用它了

**Comment by chenzeZzz** [comment]
@flyish 解决了，是node版本的问题，pomelo对node版本有限制，据说最高6.11

**Comment by flyish** [comment]
@chenzeZzz ^_^ 厉害
