### ISSUE TITLE
官方示例Chat执行npm-install.bat报错怎么解决，我已安装vc++2012

### ISSUE THREAD

**Issue by LinDCheng** [NetEase/pomelo#1027]
gyp ERR! build error
gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
gyp ERR! stack 'reg' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
gyp ERR! stack ���������ļ���
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:138:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:5)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\pomelo\chatofpomelo-websocket-tutorial-starter\game-server\node_modules\heapdump
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm info lifecycle heapdump@0.3.7~install: Failed to exec install script
npm WARN chatofpomelo@0.0.1 No description
npm WARN chatofpomelo@0.0.1 No repository field.
npm WARN chatofpomelo@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by donhwa** [comment]
不要用 visual studio 调试模式。直接使用命令行或 powershell 运行此命令

**Comment by lienhui97** [comment]
你的nodejs版本是多少?建议在10.x版本

**Comment by spikeii** [comment]
应该是缺少c++组件, 管理员打开cmd,运行 `npm install --global --production windows-build-tools`
[https://github.com/nodejs/node-gyp#installation](url)

**Comment by gocpplua** [comment]
> npm install --global --production windows-build-tools
这个不行

**Comment by donhwa** [comment]
> > npm install --global --production windows-build-tools
> > 这个不行

pomelo没有在维护了，欢迎右转 pinus.io (typescript化的pomelo)

**Comment by gocpplua** [comment]
> > > npm install --global --production windows-build-tools
> > > 这个不行
> 
> pomelo没有在维护了，欢迎右转 pinus.io (typescript化的pomelo)

玩不动啊
