### ISSUE TITLE
官方聊天服务器跑不起来

### ISSUE THREAD

**Issue by wade333777** [NetEase/pomelo#1096]
wadedeMBP:game-server wade$ pomelo start
fs.js:135
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:135:11)
    at Object.mkdir (fs.js:711:16)
    at start (/usr/local/lib/node_modules/pomelo/bin/pomelo:347:8)
    at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:65:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/pomelo/node_modules/commander/index.js:472:12)
    at Command.parse (/usr/local/lib/node_modules/pomelo/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:142:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by linkenliu** [comment]
node 版本   降到4.x

**Comment by vailin** [comment]
我修改了一下官方聊天服务器的Pomelo版本就可以跑起来了

**Comment by yaodayizi** [comment]
我也是这个错误 改成pomelo什么版本可以跑
