### ISSUE TITLE
"Error: listen EADDRINUSE :::4051\n    at Object.exports._errnoException

### ISSUE THREAD

**Issue by creatiosoft** [NetEase/pomelo#1100]
​Hi, 
I am getting below error. Please let me know, how i can solve it.
​ Server Instance:  gate-server-1
[2018-08-22 15:49:10.127] [DEBUG] pomelo - [/home/infotechcaretel/hello/game-server/app.js] =============================================================

[192.168.1.3] [2018-08-22 15:49:10.302] [DEBUG] pomelo - [/home/dd/pokerjhelloohny/game-server/app.js] info:

[192.168.1.3] [2018-08-22 15:49:10.303] [ERROR] pomelo-rpc - [/home/infotechcaretel/hello/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/acceptors/ws-acceptor.js] rpc server is error: "Error: listen EADDRINUSE :::4051\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at Server._listen2 (net.js:1271:14)\n    at listen (net.js:1307:10)\n    at Server.listen (net.js:1403:5)\n    at Object.exports.listen (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/socket.io/lib/socket.io.js:74:12)\n    at Acceptor.pro.listen (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/acceptors/ws-acceptor.js:34:21)\n    at Gateway.pro.start (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/gateway.js:49:17)\n    at Component.pro.start (/home/infotechcaretel/hello/node_modules/pomelo/lib/components/remote.js:54:15)\n    at /home/infotechcaretel/hello/node_modules/pomelo/lib/util/appUtil.js:111:19\n    at iterate (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/async/lib/async.js:123:13)\n    at /home/infotechcaretel/hello/node_modules/pomelo/node_modules/async/lib/async.js:138:29\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"

[192.168.1.3] [2018-08-22 15:49:10.307] [DEBUG] pomelo - [/home/infotechcaretel/hello/game-server/app.js] Caught exception: Error: listen EADDRINUSE :::4051
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1271:14)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at Object.exports.listen (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/socket.io/lib/socket.io.js:74:12)
    at Acceptor.pro.listen (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/acceptors/ws-acceptor.js:34:21)
    at Gateway.pro.start (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/gateway.js:49:17)
    at Component.pro.start (/home/infotechcaretel/hello/node_modules/pomelo/lib/components/remote.js:54:15)
    at /home/infotechcaretel/hello/node_modules/pomelo/lib/util/appUtil.js:111:19
    at iterate (/home/infotechcaretel/hello/node_modules/pomelo/node_modules/async/lib/async.js:123:13)
    at /home/infotechcaretel/hello/node_modules/pomelo/node_modules/async/lib/async.js:138:29
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

/home/infotechcaretel/hello/game-server/app.js:292
   app.rpc.connector.entryRemote.sendMailToDevelopers("SESSION", err.stack, function (response) {
          ^

TypeError: Cannot read property 'connector' of undefined
    at process.<anonymous> (/home/infotechcaretel/hello/game-server/app.js:292:11)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:307:26)

[2018-08-22 15:49:10.314] [WARN] pomelo - [/home/infotechcaretel/hello/node_modules/pomelo/lib/master/starter.js] child process exit with error, error code: 7, executed command: ssh

[192.168.1.5] [2018-08-22 15:49:10.335] [DEBUG] pomelo - [/home/infotechcaretel/hello/game-server/app.js] info:
​

**Comment by whtiehack** [comment]
Port 4051 is occupied. You can see if the gate process that was started before is not properly closed.
