### ISSUE TITLE
fs.js:137     throw new ERR_INVALID_CALLBACK();     ^  TypeError [ERR_INVALID_CALLBACK]: Callback must be a function     at makeCallback (fs.js:137:11)     at Object.mkdir (fs.js:719:14)     at start (/usr/local/lib/node_modules/pomelo/bin/pomelo:347:8)     at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:65:5)     at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:249:8)     at Command.emit (events.js:182:13)     at Command.parseArgs (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:472:12)     at Command.parse (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:370:21)     at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:142:9)     at Module._compile (internal/modules/cjs/loader.js:688:30)

### ISSUE THREAD

**Issue by iiCircle** [NetEase/pomelo#1125]
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.mkdir (fs.js:719:14)
    at start (/usr/local/lib/node_modules/pomelo/bin/pomelo:347:8)
    at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:65:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:249:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:472:12)
    at Command.parse (/usr/local/lib/node_modules/pomelo/node_modules/_commander@2.0.0@commander/index.js:370:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:142:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by shudingbo** [comment]
node10 有问题，可以用下面这个
https://github.com/sex-pomelo/sex-pomelo

**Comment by ChenEgou** [comment]
> node10 有问题，可以用下面这个
> https://github.com/sex-pomelo/sex-pomelo

这是个新的项目么 ？

**Comment by shudingbo** [comment]
> > node10 有问题，可以用下面这个
> > https://github.com/sex-pomelo/sex-pomelo
> 
> 这是个新的项目么 ？

新成立的社区，维护pomelo

**Comment by xhlacc** [comment]
这个问题是node新版本导致的问题。 我在版本修复了
https://github.com/xhlacc/cc-pomelo
