### ISSUE TITLE
TypeError: Cannot read property 'fetchTodaysData' of undefined

### ISSUE THREAD

**Issue by seyfer** [NetEase/pomelo#1137]
I have installed the latest version for Ubuntu 18.04 and getting this one when clicking on settings.

```
Unhandled Error
TypeError: Cannot read property 'fetchTodaysData' of undefined
    at i.getTodaysData (file:///opt/Pomello/resources/app.asar/.dist/webpack:/app/dashboard/productivity/Productivity.js:95:7)
    at i.getData (file:///opt/Pomello/resources/app.asar/.dist/webpack:/app/dashboard/productivity/Productivity.js:84:14)
    at i.componentDidUpdate (file:///opt/Pomello/resources/app.asar/.dist/webpack:/app/dashboard/productivity/Productivity.js:49:8)
    at commitLifeCycles (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:14256:22)
    at commitAllLifeCycles (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15342:7)
    at HTMLUnknownElement.callCallback (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:100:14)
    at Object.invokeGuardedCallbackDev (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:138:16)
    at invokeGuardedCallback (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:187:29)
    at commitRoot (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15481:7)
    at completeRoot (/opt/Pomello/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16496:34)
```

**Comment by seyfer** [comment]
Opps wrong git repo
