### ISSUE TITLE
when output Error: write EPIPE and process be crashed

### ISSUE THREAD

**Issue by sss316** [NetEase/pomelo#1153]
Contents of the pomelo.log：
[39mwebsocket send binary data failed: "Error: write EPIPE\n    at exports._errnoException (util.js:1020:11)\n    at WriteWrap.afterWrite (net.js:800:14)"

**Comment by sss316** [comment]
use pomelo stop output this:
mqtt socket is close, remote server host: 127.0.0.1, port: 3005
reconnect delay 1 s
mqtt socket is error, remote server host: 127.0.0.1, port: 3005
mqtt socket is close, remote server host: 127.0.0.1, port: 3005

**Comment by YunlongJiao-B** [comment]
pomelo stop// use default port 3005 
you can specific port like :
pomelo -P 6666
plus: old version pomelo not use mqtt.

**Comment by jiesms** [comment]
websocket send binary data failed: "Error: write EPIPE
出现这个问题是什么原因？有没有解决方案？

**Comment by YunlongJiao-B** [comment]
> websocket send binary data failed: "Error: write EPIPE
> 出现这个问题是什么原因？有没有解决方案？

你版本多少，换个版本吧。

**Comment by wangping0214** [comment]
跟版本啥关系？

**Comment by MirroZhou** [comment]
谢谢~已收到！
