### ISSUE TITLE
Pomelo Deployment Issue

### ISSUE THREAD

**Issue by creatiosoft** [NetEase/pomelo#1154]
Hi,

I am doing deployment on my Ubuntu system with following package and version :-

1. Pomelo ( V 1.2.3)
2 Node ( v6.17.1)
3 Npm (v 3.10.10)

I am using old/deprecated version due to project dependency. I did deployment many time on difference machine using same configuration/version, It was working fine but when I am doing on new machine now, its giving me following error even to just check pomelo version.

> rishab@risha:~$ pomelo --version
> /usr/local/lib/node_modules/pomelo/node_modules/streamroller/lib/RollingFileWriteStream.js:133
>   async _shouldRoll() {
>         ^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/node_modules/streamroller/lib/index.js:2:27)
> 

Can anyone help me how I can solve this issue?

**Comment by whtiehack** [comment]
upgrade nodejs version to 8.x

**Comment by creatiosoft** [comment]
I installed 8.2.1. I install Pomelo 1.2.1 due to some code dependency.

Now its showing me this error.

 pomelo --version
/usr/lib/node_modules/pomelo/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/pomelo/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/pomelo/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:569:30)

**Comment by sss316** [comment]
给你说下我用的版本号，测试没问题：pomelo 2.2.7 node 12.13.1 npm 6.12.1
node 只要8.11以上都没问题
