### ISSUE TITLE
websocket send binary data failed: "Error: write EPIPE

### ISSUE THREAD

**Issue by digvijay-playmoogley** [NetEase/pomelo#1169]
While player is quitting or leaving the channel then this issue occurred. It is not happening frequently but once in 2 days.

The stack trace of the same is:

```
[2020-09-28 10:22:01.890] [ERROR] pomelo - [/home/game-server/node_modules/pomelo/lib/connectors/hybridsocket.js] 
websocket send binary data failed: "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Socket.send (/home/game-server/node_modules/pomelo/lib/connectors/hybrid/tcpsocket.js:68:16)
    at Socket.sendRaw (/home/game-server/node_modules/pomelo/lib/connectors/hybridsocket.js:65:15)
    at Socket.send (/home/game-server/node_modules/pomelo/lib/connectors/hybridsocket.js:84:8)
    at Session.send (/home/game-server/node_modules/pomelo/lib/common/service/sessionService.js:529:19)
    at send (/home/game-server/node_modules/pomelo/lib/common/service/sessionService.js:427:11)
    at SessionService.sendMessage (/home/game-server/node_modules/pomelo/lib/common/service/sessionService.js:349:10)
    at Component.sendMessage (/home/game-server/node_modules/pomelo/lib/components/session.js:23:36)
    at doBatchPush (/home/game-server/node_modules/pomelo/lib/pushSchedulers/direct.js:57:20)
    at Service.schedule (/home/game-server/node_modules/pomelo/lib/pushSchedulers/direct.js:19:5)"
```
After this the clients get disconnected and there after the server will not be able to handle any further requests.

What may be the reason for this error, or any solution.

**Comment by jiesms** [comment]
websocket send binary data failed: "Error: write EPIPE
楼主，这个问题有没有解决？
