### ISSUE TITLE
"rpc request is timeout" in Pomelo 1.0 pre

### ISSUE THREAD

**Issue by nhatminh12369** [NetEase/pomelo#528]
My game-server have 1 connector server, 1 authentication server, 1 area server and use normal websocket to connect (ws)
When the client connect to the connector server, I send a rpc message from connector server to authentication server to do the login:
self.app.rpc.auth.facebookRemote.login(...);
After received the result, the connector server continues to send a rpc message to area server:
self.app.rpc.area.playerRemote.addPlayer(...);
The client login successfully, but after about 20 seconds. I received this error: 
mailboxes\ws-mailbox.js] rpc request is timeout, id: 0, host: 127.0.0.1, port: 3250(the port of area server)
mailboxes\ws-mailbox.js] rpc callback timeout, remote server host: 127.0.0.1, port: 3250 
mailstation.js] [pomelo-rpc] fail to send message

I don't have this problem with Pomelo 0.9. Only happen with Pomelo 1.0 pre. I have tried both wss and ws and experienced the same problem.

**Comment by letiennam29** [comment]
i have the same problem.

**Comment by vitahlin** [comment]
Did you solve it? @nhatminh12369 @iggyZiggy @letiennam29

**Comment by keisoftdev** [comment]
Hey @nhatminh12369 @iggyZiggy @letiennam29.
How did you solve this problem?

**Comment by vitahlin** [comment]
@keisoftdev I think your code may have some problems.

**Comment by FrancooHM** [comment]
Anyone solved this? I have the same problems but recieving this exception before: 

```
[2017-06-08 02:16:21.939] [ERROR] console -  Caught exception: RangeError: out of range index
    at RangeError (native)
    at fastCopy (/root/viatruco/viatruco-gs/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (/root/viatruco/viatruco-gs/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/root/viatruco/viatruco-gs/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

And a bit later:

```
[2017-06-08 02:16:22.381] [WARN] pomelo-rpc - rpc request is timeout, id: 908, host: 138.197.41.111, port: 6050

[2017-06-08 02:16:22.381] [ERROR] pomelo-rpc - rpc callback timeout, remote server host: 138.197.41.111, port: 6050

[2017-06-08 02:16:22.384] [ERROR] pomelo-rpc - [pomelo-rpc] fail to send message
```

cc @vitahlin @letiennam29 @py8765

**Comment by Balbo76** [comment]
me too
