### ISSUE TITLE
pomelo-rpc-zeromq长时间运行时候,会报这个错误.

### ISSUE THREAD

**Issue by charlielven** [NetEase/pomelo#556]
Interrupted system call Error: Interrupted system call
    at Socket._flush (/opt/data/games/node_modules/pomelo-rpc-zeromq/node_modules/zmq/lib/index.js:472:19)
    at Socket.send (/opt/data/games/node_modules/pomelo-rpc-zeromq/node_modules/zmq/lib/index.js:413:42)
    at pro.send (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/rpc-client/mailboxes/zmq-mailbox.js:90:17)
    at send (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/rpc-client/mailstation.js:242:13)
    at Object.exp.invokeCallback (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/util/utils.js:5:8)
    at doFilter (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/rpc-client/mailstation.js:304:11)
    at pro.dispatch (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/rpc-client/mailstation.js:260:3)
    at pro.rpcInvoke (/opt/data/games/node_modules/pomelo-rpc-zeromq/lib/rpc-client/client.js:177:17)
    at /opt/data/games/node_modules/pomelo/lib/common/service/channelService.js:431:13
    at sendMessage (/opt/data/games/node_modules/pomelo/lib/common/service/channelService.js:434:7)

**Comment by jiangzhuo** [comment]
很榮幸今天晚上線上測試服務器也因爲這個Down了

**Comment by zj8487** [comment]
建议：如果是框架代码修改，可能的话大家都提个PR吧

**Comment by ngixx** [comment]
do {
rc = zmq_send(s, &msg, flags);
} while ((rc == -1) && (zmq_errno() == EINTR));
请问一下这段代码是哪里改的？

**Comment by charlielven** [comment]
@ngixx 
http://comments.gmane.org/gmane.network.zeromq.devel/15253
这里最后一条回复中,有说明修改哪个文件
