### ISSUE TITLE
some question about mqttconnector

### ISSUE THREAD

**Issue by vietanha34** [NetEase/pomelo#660]
hi guy,
I've read some successfull case about mqttconnector from netease. It to be used for message push to client  with brazing fast and high performance. I try to make some example with mqttconector below :+1: 
- in server , I use default pomelo template for mqtt connector 

```
/**
 * Publish route for mqtt connector.
 *
 * @param  {Object}   msg     request message
 * @param  {Object}   session current session object
 * @param  {Function} next    next step callback
 * @return {Void}
 */
Handler.prototype.publish = function(msg, session, next) {
    var result = {
        topic: 'publish',
        payload: JSON.stringify({code: 200, msg: 'publish message is ok.'})
    };
  next(null, result);
};

/**
 * Subscribe route for mqtt connector.
 *
 * @param  {Object}   msg     request message
 * @param  {Object}   session current session object
 * @param  {Function} next    next step callback
 * @return {Void}
 */
Handler.prototype.subscribe = function(msg, session, next) {
    var result = {
        topic: 'subscribe',
        payload: JSON.stringify({code: 200, msg: 'subscribe message is ok.'})
    };
  next(null, result);
};
```
- in client , i use 

```
var mqtt = require('mqtt')

client = mqtt.createClient(3010, 'localhost');

client.subscribe('presence');
client.publish('presence', 'Hello mqtt');

client.on('message', function (topic, message) {
  console.log(message);
});
```
- run code and got this error in mqttconnector.js line 37 

```
[2014-12-04 20:46:21.316] [INFO] console - [Error: Invalid qos vector]
Error: Invalid qos vector
    at Object.module.exports.suback (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/node_modules/mqtt/lib/generate.js:364:12)
    at MqttServerClient.eval [as suback] (eval at <anonymous> (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/node_modules/mqtt/lib/connection.js:58:29), <anonymous>:2:26)
    at Adaptor.publish (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/connectors/mqtt/mqttadaptor.js:86:19)
    at Socket.send (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/connectors/mqttsocket.js:51:18)
    at Session.send (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/common/service/sessionService.js:496:19)
    at send (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/common/service/sessionService.js:410:11)
    at SessionService.sendMessage (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/common/service/sessionService.js:342:10)
    at null.sendMessage (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/components/session.js:23:36)
    at doBatchPush (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/pushSchedulers/direct.js:57:20)
    at Service.schedule (/Users/vietanha34/Documents/workspace/nodejs/mqtt-test/game-server/node_modules/pomelo/lib/pushSchedulers/direct.js:19:5)
```

What is a error? somebody can help me to make simple example for pomelo mqtt connector

**Comment by perzy** [comment]
@py8765 mqtt connector 相对于 socket.io connector 有什么优势呢？ 主要在客户端app开发上。
