### ISSUE TITLE
server will not connector to master when it start up before master!

### ISSUE THREAD

**Issue by zj8487** [NetEase/pomelo#682]
problems:
1,start up a logic server.
a error will print in the console
```
 [2015-01-28 09:48:11.842] [ERROR] pomelo - [/home/xxx/workspace/xxxx.server/game-server/node_modules/pomelo/lib/util/appUtil.js] fail to operate component, method: start, err: "SYSTEM_ERROR: connect ECONNREFUSED 127.0.0.1:3005\n    at Object.exports._errnoException (util.js:732:11)\n    at exports._exceptionWithHostPort (util.js:755:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:14)"
```
2,start master

3,pomelo list the process. it won't see the logic server.
  but  you can see the process though ps, or top command
@py8765 
@fantasyni

**Comment by zj8487** [comment]
maybe it is not the responsibility of pomelo.
we can do some operator in callback of app.start(). 
and we can do the work we want.
for example restart the process or shutdown the process directly.

app.start(function (err) {
        if (!err) return;
        process.exit(0);
    });
