### ISSUE TITLE
channel pushMessage error

### ISSUE THREAD

**Issue by letiennam29** [NetEase/pomelo#715]
hi everyone,
## I new start pomelo, i have error at code here in my project:

var channel= undefined;
var getChannel = function() {
    if(channel) {
        return channel;
    }
    channel = pomelo.app.get('channelService').getChannel('channel1', true);
    return channel;
};
var add_players = [];

function tick() {
    if(add_players.length > 0){
        logger.warn("^^^^^^^^^^^^^^^^^^^^^");
        logger.warn(channel.getMembers().length);
        logger.warn("^^^^^^^^^^^^^^^^^^^^^");
        getChannel().pushMessage({ route: 'add_player',code: Code.OK});//ERROR at HERE
    }
}
setInterval(tick, 1000);
## I get show errror below:

[2015-04-09 14:46:08.789] [ERROR] pomelo - [.../node_modules/pomelo/lib/common/service/channelService.js] [pushMessage] fail to dispatch msg to serverId: 1, err:Error: rpc failed with error code: 2
    at failfast (.../node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:151:27)
    at module.exports (.../node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:24:10)
    at emit (events.js:118:17)
    at pro.dispatch (..../node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:228:12)
    at pro.rpcInvoke (..../node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/client.js:172:17)
    at ..../node_modules/pomelo/lib/common/service/channelService.js:434:13
    at sendMessage .../node_modules/pomelo/lib/common/service/channelService.js:437:7)
    at sendMessageByGroup (.../node_modules/pomelo/lib/common/service/channelService.js:444:7)
    at Channel.pushMessage (.../node_modules/pomelo/lib/common/service/channelService.js:331:3)
    at tick (..../app/servers/area/remote/playerRemote.js:53:22)

**Comment by wuxian** [comment]
getChannel().pushMessage('add_player', {code: Code.OK},function() {});//ERROR at HERE
route为第一参数

**Comment by letiennam29** [comment]
tks @wuxian, i've pass error. Because I Add user to channel wrong sid(sid of server connector).

before:
var serverId =  app.get('serverId').split('-')[2];
channel.add(player_id, serverId );

correct:
var serverId =  app.get('serverId');
channel.add(player_id, serverId );
