### ISSUE TITLE
pomelo-admin-web启动失败

### ISSUE THREAD

**Issue by sam2668** [NetEase/pomelo#729]
pomelo-admin-web apple$ node app

module.js:340
    throw err;
          ^
Error: Cannot find module 'finalhandler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/apple/Desktop/NodeJS/pomelo-admin-web/node_modules/express/node_modules/connect/lib/proto.js:12:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by letiennam29** [comment]
You move to directory pomelo-admin-web after install need module in package.json by command:
npm install --save

**Comment by sam2668** [comment]
Thank you for reply!!!

2015-06-17 19:28 GMT+08:00 letiennam29 <notifications@github.com>:
