### ISSUE TITLE
Cannot call method 'forwardMessage' of undefined

### ISSUE THREAD

**Issue by Wsquan** [NetEase/pomelo#733]
服务器平时正常运行,但在放置运行一段时间后会出现如下BUG,将近上线了,游戏服务器不够稳定,请问该如何解决?
```
data:    game-server/app.js:7258 - [2015-06-20 22:38:26.926] [ERROR] pomelo - [/home/server/game/game-server/node_modules/pomelo/lib/server/server.js] fail to forward message:TypeError: Cannot call method 'forwardMessage' of undefined
data:    game-server/app.js:7258 -     at doForward (/home/server/game/game-server/node_modules/pomelo/lib/server/server.js:334:50)
data:    game-server/app.js:7258 -     at dispatch (/home/server/game/game-server/node_modules/pomelo/lib/server/server.js:103:7)
data:    game-server/app.js:7258 -     at next (/home/server/game/game-server/node_modules/pomelo/lib/common/service/filterService.js:50:7)
data:    game-server/app.js:7258 -     at Service.beforeFilter (/home/server/game/game-server/node_modules/pomelo/lib/common/service/filterService.js:65:3)
data:    game-server/app.js:7258 -     at beforeFilter (/home/server/game/game-server/node_modules/pomelo/lib/server/server.js:242:8)
data:    game-server/app.js:7258 -     at pro.globalHandle (/home/server/game/game-server/node_modules/pomelo/lib/server/server.js:112:3)
data:    game-server/app.js:7258 -     at Component.globalHandle (/home/server/game/game-server/node_modules/pomelo/lib/components/server.js:74:14)
data:    game-server/app.js:7258 -     at handleMessage (/home/server/game/game-server/node_modules/pomelo/lib/components/connector.js:295:15)
data:    game-server/app.js:7258 -     at null.<anonymous> (/home/server/game/game-server/node_modules/pomelo/lib/components/connector.js:239:5)
data:    game-server/app.js:7258 -     at emit (events.js:95:17)
```

**Comment by wuxian** [comment]
这个一般是客户端发错了消息，因为按POMELO这个走，会有两个连接，一个是GATE的，一个是CONNECTOR的，比如把给scene的消息发给了gate就会报这个错，排查下这个应该就能找到问题
