### ISSUE TITLE
pomelo restart 有时候会失败

### ISSUE THREAD

**Issue by skyblue** [NetEase/pomelo#734]
pomelo restart -i srv-0

try to connect 127.0.0.1:3005
{ message: 'all servers start failed.',
  stack: 'Error: all servers start failed.
    at null.cb (/node_modules/pomelo/lib/modules/console.js:195:32)
    at CountDownLatch.done (/node_modules/pomelo/lib/util/countDownLatch.js:32:10)
    ...

**Comment by jonahzheng** [comment]
我也碰到了，有时会提示某一个服务 connector-server-1，
通过pomelo add 也无法加入
