### ISSUE TITLE
下载了事例跑起来有问题 

### ISSUE THREAD

**Issue by bear-qv** [NetEase/pomelo#744]
这个教程：https://github.com/netEase/pomelo/wiki/chat%E6%BA%90%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8E%E5%AE%89%E8%A3%85

[2015-07-27 16:46:40.140] [ERROR] console -  Caught exception: TypeError: Cannot convert undefined or null to object
    at copyArray (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protocol.js:266:11
)
    at Object.Package.decode (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\pomelo-protocol\lib\protoc
ol.js:138:7)
    at WebSocket.<anonymous> (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\lib\connectors\hybridsocket.js:40:21)
    at WebSocket.emit (events.js:110:17)
    at Receiver.self._receiver.onbinary (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\WebSocke
t.js:549:10)
    at Receiver.opcodes.2.finish (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:448
:14)
    at Receiver.expectHandler (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:433:33
)
    at Receiver.add (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\Receiver.js:93:24)
    at Socket.firstHandler (D:\Program Manager\Pomelo\chatofpomelo-websocket\game-server\node_modules\pomelo\node_modules\ws\lib\WebSocket.js:524:22)
    at Socket.emit (events.js:107:17)

**Comment by bear-qv** [comment]
我看到了。
A simple chat room experiment using pomelo framework and html5. The chat server currently runs on nodejs v0.8, and should run fine on the latest stable as well.

顺便问一下有没有新的例子@py8765

**Comment by bear-qv** [comment]
http://nodejs.netease.com/topic/5552edc7710651e80f6c3ad2 这里靠谱，突然觉得社区活跃很多。其他的平台都有些惨淡
