### ISSUE TITLE
session importAll 报错: session does not exist

### ISSUE THREAD

**Issue by smilence86** [NetEase/pomelo#765]
错误日志：

[2015-10-21 17:31:32.260] [ERROR] pomelo-biz - [/data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js] 【客户端: ios	55c842ebe55baa64328b460f 连接异常】error：Error: nickname:， uid:55c842ebe55baa64328b460f, set rid: 55c9a98de58a3a8e118b464b for session service, serverId:connector-server-12. failed: 

    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:125:39
    at Object.utils.invokeCallback (/data/www/htdocs/chat/node_modules/pomelo/lib/util/utils.js:15:8)
    at SessionService.importAll (/data/www/htdocs/chat/node_modules/pomelo/lib/common/service/sessionService.js:235:11)
    at FrontendSession.pushAll (/data/www/htdocs/chat/node_modules/pomelo/lib/common/service/sessionService.js:615:27)
    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:123:33
    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:135:23
    at tryCatcher (/data/www/htdocs/chat/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

我的业务代码connector的enter方法：
```javascript
Promise...
   ....
.then(function(){
        session.set('uid', uid);
        session.set('client_os', client_os);
        session.bind(uid);
        session.on('closed', onUserLeave.bind(null, self.app));
})
.then(function(rids){
            if(rids.length){
                for(var i in rids){
                    (function(rid){
                        session.set('rid', rid);
                        //与后端session同步
                        session.pushAll(function(err){
                            if(err){
                                throw new Error('nickname:' + nickname + '， uid:' + uid + ', set rid: ' + rid + ' for session service, serverId:' + serverId + '. failed: \n', err.valueOf());
                            }else{
                                //put user into channel
                                self.app.rpc.chat.chatRemote.add(session, uid, serverId, rid, true, function(users){
                                    if(users.indexOf(uid) < 0){
                                        bizlogger.error('添加用户[%s]到群组[%s]失败', uid, rid);
                                    }
                                });
                            }
                        });
                    })(rids[i]);
                }
                //直接将群组列表id写到session中，客户端退出时清理工作需要
                session.set('rids', rids);
            }
        }).then(function(){
                return new Promise(function(resolve, reject){
                //与后端session同步
                session.pushAll(function(err){
                    if(err){
                        return reject(new Error('uid:' + uid + ', 同步session出错：\n' + err.valueOf()));
                    }
                    resolve();
                });
            });
        }).catch(function(err){
                console.error(err);
        });
```

pomelo底层代码，在 node_modules/pomelo/lib/common/service/sessionService.js 235 行：
```javascript
SessionService.prototype.importAll = function(sid, settings, cb) {
  var session = this.sessions[sid];
  if(!session) {
    utils.invokeCallback(cb, new Error('session does not exist, sid: ' + sid));
    return;
  }

  for(var f in settings) {
    session.set(f, settings[f]);
  }
  utils.invokeCallback(cb);
};
```

pomelo是1.2.0，部署在2台物理机，connector有20个。这个问题比较坑的地方在于大多数人遇不到，少部分人才会出现，而别人又在外省，不好排查。

**Comment by py8765** [comment]
session不存在 应该是连接断开了

**Comment by smilence86** [comment]
昨晚简化了代码，依然会出现 pushAll 错误。

enter方法：
```javascript
Promise...
   ....
.then(function(){
    session.set('uid', uid);
    session.set('client_os', client_os);
    session.bind(uid);
    session.on('closed', onUserLeave.bind(null, self.app));
}).then(function(rids){
    if(rids.length){
        //直接将群组列表id写到session中，客户端退出时清理工作需要
        session.set('rids', rids);
        var promises = rids.map(function(rid){
            return new Promise(function(resolve, reject){
                session.set('rid', rid);
                self.app.rpc.chat.chatRemote.add(session, uid, serverId, rid, true, function(users){
                    if(users.indexOf(uid) < 0){
                        bizlogger.error('(' + uid + ')加入群组(' + rid + ')失败，serverId(' + serverId + ')');
                        return reject('(' + uid + ')加入群组(' + rid + ')失败，serverId(' + serverId + ')');
                    }
                    resolve('(' + uid + ')加入群组(' + rid + ')成功');
                });
            });
        });
        return Promise.settle(promises).then(function(results){
            results.forEach(function(res){
                if(res.isRejected()){
                    bizlogger.error('ERROR:%j', res.reason());
                }else if(res.isFulfilled()){
                    //bizlogger.info(res.value());
                }
            });
        });
    }
}).then(function(){
    return new Promise(function(resolve, reject){
        //与后端session同步
        session.pushAll(function(err){
            if(err){
                return reject(new Error('uid:' + uid + ', 同步session出错：\n' + err.valueOf()));
            }
            resolve();
        });
    });
}).then(function(){
    log(client_os + '【客户端' + uid + '连接成功】');
    next(null, {code: 200, error: false});
}).catch(function(e){
    bizlogger.error('【客户端: ' + client_os + '\t' + uid + ' 连接异常】error：' + e.stack);
    next(null, {code: 500, error: true});
});
```

pushAll 出错：
[2015-10-23 09:39:13.416] [ERROR] pomelo-biz - [/data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js] 【客户端: android54412aefe419beed058b4567 连接异常】error：Error: uid:54412aefe419beed058b4567, 同步session出错：
Error: session does not exist, sid: 980
    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:173:39
    at Object.utils.invokeCallback (/data/www/htdocs/chat/node_modules/pomelo/lib/util/utils.js:15:8)
    at SessionService.importAll (/data/www/htdocs/chat/node_modules/pomelo/lib/common/service/sessionService.js:235:11)
    at FrontendSession.pushAll (/data/www/htdocs/chat/node_modules/pomelo/lib/common/service/sessionService.js:615:27)
    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:171:25
    at tryCatcher (/data/www/htdocs/chat/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:69:37)
    at /data/www/htdocs/chat/app/servers/connector/handler/entryHandler.js:169:20
    at tryCatcher (/data/www/htdocs/chat/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/data/www/htdocs/chat/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/www/htdocs/chat/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)


@py8765 session不存在连接断开了，刚进入enter就断开？

**Comment by smilence86** [comment]
已解决，参照：http://nodejs.netease.com/topic/56275de142a25b9a1432ad96 - automatic!

**Comment by smilence86** [comment]
已解决，参照：http://nodejs.netease.com/topic/56275de142a25b9a1432ad96 - automatic!

**Comment by vitrolbe** [comment]
这个是怎么修复的
