### ISSUE TITLE
Auto remove server area just  after add server area.

### ISSUE THREAD

**Issue by letiennam29** [NetEase/pomelo#782]
Hi @py8765, You can help me!

This is is a part of my project:

![image](https://cloud.githubusercontent.com/assets/5987534/11985331/37cca68c-a9f6-11e5-9c1e-6c12fa3a5af0.png)

I get an error when start connector and area on 2 different server. 

Begin Client request router to area, server reponse data success.
But when I stop all server type area, client keep connection and request. I get error below:

[2015-12-24 04:40:01.692] [DEBUG] pomelo - [/home/namlt/OnePiece/game-server/node_modules/pomelo/lib/components/connector.js] [connector-server-1] send message reqId: 23, route: area.userHandler.getUserInfo, msg: {"code":500}, receivers: [1], opts: {"type":"response","userOptions":{},"isResponse":true}
[2015-12-24 04:40:01.692] [WARN] pomelo-rpc - [/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js] rpc request is timeout, id: 1, host: 172.xx.xx.xx, port: 5253
[2015-12-24 04:40:01.693] [ERROR] pomelo-rpc - [/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js] rpc callback timeout, remote server host: 172.xx.xx.xx., port: 5253
[2015-12-24 04:40:01.693] [ERROR] pomelo-rpc - [/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js] [pomelo-rpc] fail to send message
[2015-12-24 04:40:01.694] [ERROR] pomelo-rpc - [/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js] rpc failed with error, remote server: server1-04, msg: {"namespace":"sys","serverType":"area","service":"msgRemote","method":"forwardMessage","args":[{"id":28,"route":"area.userHandler.getUserInfo","body":{"uid":123456,"timestamp":1450906771906}},{"id":1,"frontendId":"connector-server-1","uid":"778","settings":{"serverGame":"1"}}]}, error code: 5
[2015-12-24 04:40:01.697] [ERROR] pomelo - [/home/namlt/OnePiece/game-server/node_modules/pomelo/lib/server/server.js] fail to process remote message:Error: rpc failed with error code: 5
    at failfast (/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:151:27)
    at module.exports (/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:24:10)
    at emit (events.js:118:17)
    at /home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:252:14
    at Object.exp.invokeCallback (/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/util/utils.js:5:8)
    at null.<anonymous> (/home/namlt/OnePiece/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js:178:11)
    at Timer.listOnTimeout (timers.js:119:15)

Then I start servers area, server connector have receive signal add server area, but after connector receive timeout and it removeServer servers area.

That's the picture I illustrate its working process:
![image](https://cloud.githubusercontent.com/assets/5987534/11985338/57e945a6-a9f6-11e5-9f2a-7076dccf2cec.png)

![image](https://cloud.githubusercontent.com/assets/5987534/11985390/e8dbca20-a9f6-11e5-8e00-bda5b8288677.png)

![image](https://cloud.githubusercontent.com/assets/5987534/11985410/12390fe0-a9f7-11e5-9544-f8c519e35bc4.png)

Hope you can help me!

**Comment by letiennam29** [comment]
I run many area, but kill all area. but when kill all area, master failed to do receive all areas disconnected.
It takes master 30s to do receive all disconnection.

Therefore the client request to fail.

**Comment by letiennam29** [comment]
@py8765 have way to overcome it?

**Comment by minhtc** [comment]
hi @letiennam29 Did you resolved this issue?
