### ISSUE TITLE
Cannot run Treasure here is what i get error

### ISSUE THREAD

**Issue by MudaliarArun** [NetEase/pomelo#792]
I am able to run the hello world app properly, not able to run Treasure app.
Kindly find log file.
What happens when i start game-server

F:\Android\Projects\pomelo\treasures\game-server>pomelo start
module.js:328
    throw err;
    ^

Error: Cannot find module 'pomelo'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (F:\Android\Projects\pomelo\treasures\game-server\app.
js:1:76)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
[npm-debug.zip](https://github.com/NetEase/pomelo/files/86059/npm-debug.zip)

**Comment by trinhvietnam** [comment]
same my problem
I resolve by copy folder pomelo compliled in ubuntu to folder node_modules of project
![pomelo](https://cloud.githubusercontent.com/assets/5329583/12356120/77371ad4-bbd3-11e5-8b7f-a934dd1549c7.png)

And here is pomelo folder 
https://drive.google.com/file/d/0B-hxz6ee5n8_TEtzdllzZGo5bjg/view?usp=sharing

**Comment by MudaliarArun** [comment]
@trinhvietnam thank you for your inputs, is the IDE you are using intelij ?

**Comment by trinhvietnam** [comment]
@MudaliarArun i'm using webstorm https://www.jetbrains.com/webstorm/

**Comment by MudaliarArun** [comment]
@trinhvietnam thank you for your valuable inputs, surely i will try webstrom, i have just started learning nodejs
