### ISSUE TITLE
node app时报nodelua找不到

### ISSUE THREAD

**Issue by SimaBenteng** [NetEase/pomelo#828]
```
LiJingdeiMac:ccjhServer lijing$ node app
[2016-04-27 18:45:06.293] [INFO] pomelo - [/Users/lijing/Documents/ccjhServer/node_modules/pomelo/lib/application.js] application inited: "master-server-1"

module.js:340
    throw err;
    ^
Error: Cannot find module '../build/Debug/nodelua'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lijing/Documents/ccjhServer/node_modules/nodelua/lib/index.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lijing/Documents/ccjhServer/app/LuaFrameWork/NodeJsCallLuaMain.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lijing/Documents/ccjhServer/app.js:62:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

请问，是不是我少安装了什么

**Comment by SimaBenteng** [comment]
本机系统为mac。运行pomelo聊天例子正常。
当前尝试运行的项目在Ubuntu系统中也可正常运行。
根据报错提示，看了下项目中，存在nodeLua.node
怀疑是不是缺了什么东西导致nodeLua无法加载。
