### ISSUE TITLE
utils.js 库发生异常 在安装的时候出错。

### ISSUE THREAD

**Issue by lilaizhencn** [NetEase/pomelo#839]
Error: EINVAL, invalid argument
    at /usr/local/lib/node_modules/pomelo/lib/util/utils.js:316:19
    at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/lib/util/utils.js:327:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pomelo/bin/pomelo:14:11)
    at Module._compile (module.js:456:26)

**Comment by 602884291** [comment]
本地win10内置ubuntu中安装的。 在阿里云centos安装完后只有 init命令没有其他的命令
