### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Mikejinhua** [NetEase/pomelo#841]
按这个教程来弄的https://github.com/NetEase/pomelo/wiki/pomelo%E7%9A%84HelloWorld ，
到最后执行那个HellowWorld的Demo报错了。
执行
$ cd game-server
$ pomelo start
显示这样的
D:\ServerFramework\Pomelo\HelloWorld\game-server>pomelo start
(node:8508) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
[2016-05-18 00:07:33.828] [INFO] pomelo - [D:\ServerFramework\Pomelo\HelloWorld\game-server\node_modules\pomelo\lib\application.js] application inited: "771fc560-1c49-11e6-a6d4-35d62139860d"

[2016-05-18 00:07:33.892] [INFO] pomelo - [D:\ServerFramework\Pomelo\HelloWorld\game-server\node_modules\pomelo\lib\monitors\zookeepermonitor.js] try to start monitor server

[2016-05-18 00:07:48.893] [INFO] pomelo - [D:\ServerFramework\Pomelo\HelloWorld\game-server\node_modules\pomelo\lib\monitors\zookeepermonitor.js] connect to zookeeper timeout

[2016-05-18 00:07:48.897] [ERROR] pomelo - [D:\ServerFramework\Pomelo\HelloWorld\game-server\node_modules\pomelo\lib\util\appUtil.js] fail to operate component, method: start, err: "Error: 771fc560-1c49-11e6-a6d4-35d62139860d cannot connect to zookeeper.\n    at Timeout._onTimeout (D:\ServerFramework\Pomelo\HelloWorld\game-server\node_modules\pomelo\lib\monitors\zookeepermonitor.js:59:30)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)"
运行环境win10

**Comment by NextZeus** [comment]
我的操作系统是mac osx  
安装了 zookeeper 之后 就没有报错了。

Install the App

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
and press enter/return key. Wait for the command to finish.
Run:
brew install zookeeper
Done! You can now use zookeeper.

**Comment by fantasyni** [comment]
现在应该好了
