### ISSUE TITLE
Pomelo Application Kill

### ISSUE THREAD

**Issue by creatiosoft** [NetEase/pomelo#861]
Hello Everyone

We has been launched 2 game's using Pomelo & never faced this kind of issue which i am going to write . I setuped the server with exactly same configuration ( Distributed) as i previously did in my other two game's. I restarted my server tommorow & that time application server was working fine. Today my user start complaining that game is not working & on terminal i am seeing this issue.

Fail to connect to admin console server.Error: connect ECONNREFUSED 127.0.0.1:3005
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
ubuntu@ip-172-31-38-217:~$  
ubuntu@ip-172-31-38-217:~$ pomelo list
try to connect 127.0.0.1:3005
Fail to connect to admin console server.Error: connect ECONNREFUSED 127.0.0.1:3005
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
ubuntu@ip-172-31-38-217:~$ 

Please let me know what i am doing wrong.

**Comment by honwsn** [comment]
process.on('uncaughtException', function (err) {
    console.log(err);
});
