### ISSUE TITLE
安装 lordofpomelo 出错 

### ISSUE THREAD

**Issue by gabrieltong** [NetEase/pomelo#864]
node 6.3.1
npm 3.10.3
python 2.7.10
mysql 5.7.12

```
npm install

> ndump@0.0.2 install /Users/tongyang/Sites/lordofpomelo/game-server/node_modules/ndump
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/ndump/src/node_dump.o
In file included from ../src/node_dump.cc:5:
../src/heap_dump.h:19:54: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> WriteSnapshot(const Arguments& args);
                                                     ^~~~~~~~~
                                                     v8::internal::Arguments
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:145:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/node_dump.cc:6:
../src/cpu_dump.h:19:58: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> DeleteAllProfiles(const Arguments& args);
                                                         ^~~~~~~~~
                                                         v8::internal::Arguments
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:145:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/node_dump.cc:6:
../src/cpu_dump.h:20:51: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> GetProfile(const Arguments& args);
                                                  ^~~~~~~~~
                                                  v8::internal::Arguments
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:145:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/node_dump.cc:6:
../src/cpu_dump.h:21:55: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> StartProfiling(const Arguments& args);
                                                      ^~~~~~~~~
                                                      v8::internal::Arguments
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:145:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/node_dump.cc:6:
../src/cpu_dump.h:22:54: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> StopProfiling(const Arguments& args);
                                                     ^~~~~~~~~
                                                     v8::internal::Arguments
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:145:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/node_dump.cc:18:15: error: calling a protected constructor of class 'v8::HandleScope'
                HandleScope scope;
                            ^
/Users/tongyang/.node-gyp/6.3.1/include/node/v8.h:904:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
6 errors generated.
make: *** [Release/obj.target/ndump/src/node_dump.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tongyang/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/tongyang/.nvm/versions/node/v6.3.1/bin/node" "/Users/tongyang/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tongyang/Sites/lordofpomelo/game-server/node_modules/ndump
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
lord_of_pomelo@0.3.0 /Users/tongyang/Sites/lordofpomelo/game-server
└── (empty)

npm WARN lord_of_pomelo@0.3.0 No description
npm WARN lord_of_pomelo@0.3.0 No repository field.
npm WARN lord_of_pomelo@0.3.0 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/tongyang/.nvm/versions/node/v6.3.1/bin/node" "/Users/tongyang/.nvm/versions/node/v6.3.1/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! ndump@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ndump@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ndump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ndump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ndump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tongyang/Sites/lordofpomelo/game-server/npm-debug.log
```

**Comment by 7demo** [comment]
不确定是不是必须linux，可以试下。
我是node 0.10.36 ,  npm 1.3.6 ,  game server 可以跑起来

**Comment by gabrieltong** [comment]
我的是 mac 系统 ，nvm 装的nodejs ，我试试低版本

**Comment by gabrieltong** [comment]
@7demo 确实可以
