### ISSUE TITLE
端口占用

### ISSUE THREAD

**Issue by zyf0330** [NetEase/pomelo#880]
qq 占用了4300端口，而 pomelo 一个服务器用使用了4300端口，而启动不会报错，执行代码才会报错。

**Comment by fantasyni** [comment]
晕，改下servers.json呀

**Comment by zyf0330** [comment]
这样的回答真是不敢恭维。好像这不是个问题一样。不过反正是个被放弃的项目了。

**Comment by fantasyni** [comment]
@zyf0330 启动应该是会报错的，这个是nodejs层要报的，不知道你具体什么情况

**Comment by zyf0330** [comment]
我没看到任何报错，就是指定了使用4300端口。非前端服务器。

**Comment by fantasyni** [comment]
@zyf0330 node 版本 ?，用最新版本pomelo试试

**Comment by zyf0330** [comment]
待我重新使用了看看

**Comment by zyf0330** [comment]
现在使用最新版本 pomelo。
QQ.exe 是在监听 4300 端口，所以可能 node 不会发现这个问题。

**Comment by fantasyni** [comment]
@zyf0330 qq 监听的可能是udp的端口，执行的时候报什么错误？我也去试试

**Comment by zyf0330** [comment]
这是报错信息
```
[2017-01-23 13:46:20.618] [ERROR] pomelo-rpc - [C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailboxes\ws-mailbox.js] rpc socket is error, remote server host: 127.0.0.1, port: 4300

[2017-01-23 13:46:20.619] [ERROR] pomelo-rpc - [C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailstation.js] [pomelo-rpc] fail to send message

[2017-01-23 13:46:20.619] [ERROR] pomelo-rpc - [C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\failureProcess.js] rpc failed with error, remote server: world-server-1, msg: {"namespace":"
sys","serverType":"world","service":"msgRemote","method":"forwardMessage","args":[{"id":8,"type":0,"compressRoute":1,"route":"world.WorldHandler.enter","body":{},"compressGzip":0},{"id":1,"frontendId":"entry-server-1","uid"
:null,"settings":{}}]}, error code: 5

[2017-01-23 13:46:20.622] [ERROR] pomelo - [C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo\lib\server\server.js] fail to process remote message:Error: rpc failed with error code: 5
    at failfast (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\failureProcess.js:151:27)
    at module.exports (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\failureProcess.js:24:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailstation.js:252:14
    at Object.exp.invokeCallback (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\util\utils.js:5:8)
    at pro.send (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailboxes\ws-mailbox.js:101:11)
    at send (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailstation.js:247:13)
    at Object.exp.invokeCallback (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\util\utils.js:5:8)
    at doFilter (C:\Programming\project\Node\crescent-pomelo\node_modules\pomelo-rpc\lib\rpc-client\mailstation.js:348:11)
```
