### ISSUE TITLE
use "pomelo init AAA" failed

### ISSUE THREAD

**Issue by zhouciming** [NetEase/pomelo#890]
I installed the latest nodejs and pomelo on windows7 this afternoon. And error occurs when I create a new project using "pomelo init HelloWorld", errors listed here:

E:\program\nodejs>pomelo init HelloWorld
E:\profile\AppData\Roaming\npm\node_modules\pomelo\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (E:\profile\AppData\Roaming\npm\node_modules\pomelo\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\profile\AppData\Roaming\npm\node_modules\pomelo\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:573:32)

Can anybody help me? Thank you very much.

**Comment by zhouciming** [comment]
The reason here is EventEmitter is undefined, and EventEmitter comes from process.EventEmitter in store.js on line 18. How did it happen?

**Comment by kungercn** [comment]
i have the problem like that too.
In mac osx,I install pomelo in accordance with the wiki,but  create  project using "pomelo init HelloWorld",it error

**Comment by kungercn** [comment]
pomelo version 1.2.3,node 7.2.0

**Comment by mzget** [comment]
node 6.7+ deprecated EventEmitter module. may be you just use node 4.0+ instead.

**Comment by zhouciming** [comment]
Thank you for your answer. But I think it must have solutions for node7, and where can we find it?

**Comment by fantasyni** [comment]
this problem will be upgraded, thanks
