### ISSUE TITLE
error Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by linxiaobai** [NetEase/pomelo#898]
```
8357 silly rollbackFailedOptional Starting
8358 silly rollbackFailedOptional Finishing
8359 silly runTopLevelLifecycles Finishing
8360 silly install printInstalled
8361 warn optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\pomelo\node_modules\bufferutil):
8362 warn optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
8362 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY:
8363 verbose optional Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the bufferutil package,
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node-gyp rebuild
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs bufferutil
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls bufferutil
8363 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
8364 verbose stack Error: heapdump@0.3.7 install: `node-gyp rebuild`
8364 verbose stack Exit status 1
8364 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
8364 verbose stack     at emitTwo (events.js:106:13)
8364 verbose stack     at EventEmitter.emit (events.js:191:7)
8364 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
8364 verbose stack     at emitTwo (events.js:106:13)
8364 verbose stack     at ChildProcess.emit (events.js:191:7)
8364 verbose stack     at maybeClose (internal/child_process.js:877:16)
8364 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
8365 verbose pkgid heapdump@0.3.7
8366 verbose cwd D:\dev\workspaces\gitworkspace\pomelo
8367 error Windows_NT 6.1.7601
8368 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
8369 error node v6.9.4
8370 error npm  v3.10.10
8371 error code ELIFECYCLE
8372 error heapdump@0.3.7 install: `node-gyp rebuild`
8372 error Exit status 1
8373 error Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
8373 error Make sure you have the latest version of node.js and npm installed.
8373 error If you do, this is most likely a problem with the heapdump package,
8373 error not with npm itself.
8373 error Tell the author that this fails on your system:
8373 error     node-gyp rebuild
8373 error You can get information on how to open an issue for this project with:
8373 error     npm bugs heapdump
8373 error Or if that isn't available, you can get their info via:
8373 error     npm owner ls heapdump
8373 error There is likely additional logging output above.
8374 verbose exit [ 1, true ]
```
win7安装pomelo装了一天了，这个问题搞不明白是为什么。
google也查了一天了，M VC++2010 X64，.NET Framework 2.0 SDK也装了，有没有哪个大哥给小弟一点指点。

**Comment by linxiaobai** [comment]
装个vc++ Build Tools好像可以了  下载地址:http://landinghub.visualstudio.com/visual-cpp-build-tools
跟node-gyp有关，详见:
https://github.com/nodejs/node-gyp
