### ISSUE TITLE
Pomelo rpc error

### ISSUE THREAD

**Issue by saruno** [NetEase/pomelo#902]
When i send data to client, sometime i got an error 

channelService sendMessageByGroup route: user_info, msg: {"money":0,"point":0,"title":"Huy ÄÃ o","avatar":"https://graph.facebook.com/1908231799405375/picture?width=100","level":0,"secret_key":null,"role_id":0,"coupon":0}, groups: {"connector-server-1":["fb_1908231799405375"]}---->Error: room channelService sendMessageByGroup route: user_info, msg: {"money":0,"point":0,"title":"Huy ÄÃ o","avatar":"https://graph.facebook.com/1908231799405375/picture?width=100","level":0,"secret_key":null,"role_id":0,"coupon":0}, groups: {"connector-server-1":["fb_1908231799405375"]}
    at CountDownLatch.cb (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/lib/common/service/channelService.js:405:32)
    at CountDownLatch.done (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/lib/util/countDownLatch.js:33:10)
    at /usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/lib/common/service/channelService.js:415:15
    at Object.exp.invokeCallback (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/util/utils.js:5:8)
    at MailStation.failfast (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:151:8)
    at MailStation.module.exports (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProcess.js:24:10)
    at emitMany (events.js:127:13)
    at MailStation.emit (events.js:201:7)
    at /usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:252:14
    at Object.exp.invokeCallback (/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/util/utils.js:5:8)

Pomelo-rpc log like that 

[2017-01-21 23:22:51.625] [WARN] pomelo-rpc - [33m172: [/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js] [39mrpc request is timeout, id: 1364, host: 127.0.0.1, port: 3150
[2017-01-21 23:22:51.625] [ERROR] pomelo-rpc - [31m177: [/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js] [39mrpc callback timeout, remote server host: 127.0.0.1, port: 3150
[2017-01-21 23:22:51.626] [ERROR] pomelo-rpc - [31m251: [/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js] [39m[pomelo-rpc] fail to send message
[2017-01-21 23:22:51.627] [ERROR] pomelo-rpc - [31m150: [/usr/pomelo_prj/showtimes_nodejs/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/failureProc

What's wrong with my pomelo server ? ("pomelo":"1.1.9")

**Comment by fantasyni** [comment]
client may be not online, then this push message failed, then rpc failed

**Comment by fantasyni** [comment]
i will follow this issue and locate the problem point

**Comment by saruno** [comment]
My server structure like that : Gate (Frontend) -> Connector (Frontend) -> Room (Backend, where logic is processed). Error is happened when push message to client from Room.

**Comment by fantasyni** [comment]
@saruno ok, i see, i will check this problem

**Comment by jsnoops** [comment]
I'm getting errors when my backend is pushing to the front end as well.. was this ever fixed?
