### ISSUE TITLE
Getting an error when I'm trying to run lordofpomelo game server

### ISSUE THREAD

**Issue by jsnoops** [NetEase/pomelo#909]
gotti@the-gotti:~/WebstormProjects/lordofpomelo/lordofpomelo/game-server$ pomelo start
[2017-02-05 17:32:41.103] [INFO] pomelo - [/usr/lib/node_modules/pomelo/lib/application.js] application inited: "master-server-1"

/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app/dao/mysql/dao-pool.js:8
	return _poolModule.Pool({
	                   ^

TypeError: Class constructor Pool cannot be invoked without 'new'
    at Object.createMysqlPool (/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app/dao/mysql/dao-pool.js:8:21)
    at Object.NND.init (/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app/dao/mysql/mysql.js:13:32)
    at Object.sqlclient.init (/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app/dao/mysql/mysql.js:50:7)
    at Object.<anonymous> (/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app.js:123:50)
    at Object.Application.configure (/usr/lib/node_modules/pomelo/lib/application.js:590:10)
    at Object.<anonymous> (/home/gotti/WebstormProjects/lordofpomelo/lordofpomelo/game-server/app.js:122:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by fantasyni** [comment]
i will check it
