### ISSUE TITLE
RPC invocation failed while connecting to master server from area server

### ISSUE THREAD

**Issue by nurulnabi** [NetEase/pomelo#910]
I am trying to connect to the master server from my area server. For this I tried to invoke rpc but an error showed up indicating master is not found. I just want to connect to master to fulfill my purpose. Kindly tell me the way an area server can connect to the master and also tell what API's master provides that can be called via rpc invocation

**Comment by fantasyni** [comment]
master server is not load rpc proxy component by default 
master can invoke area, by setting  
```
app.configure('production|development', 'master', function() {
       app.load(pomelo.proxy, app.get('proxyConfig'));
});
```
however, area can not inovke master by rpc  
you can try to use pomelo-admin modules

**Comment by nurulnabi** [comment]
@fantasyni , I want to add a chat server from connector server or a connector server from gate server then how can that be done?

**Comment by fantasyni** [comment]
@nurulnabi simply, you can try to invoke pomelo add command in exec child process

**Comment by nurulnabi** [comment]
@fantasyni 
I just called the following in my gate server,

`var servers = [{"id":"added-connector-server-1", "host":"127.0.0.1", "port":4055, "clientPort": 3055, "frontend": true}];
	this.app.addServers(servers);`

Then the following error showed up, what does it mean? Kindly elaborate.
_**Caught exception: TypeError: Path must be a string. Received undefined**
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.exp.getUserRemotePath (/home/noor/stuffs/node_modules/pomelo/lib/util/pathUtil.js:25:16)
    at getProxyRecords (/home/noor/stuffs/node_modules/pomelo/lib/components/proxy.js:223:21)
    at genProxies (/home/noor/stuffs/node_modules/pomelo/lib/components/proxy.js:184:23)
    at Component.pro.addServers (/home/noor/stuffs/node_modules/pomelo/lib/components/proxy.js:112:3)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Object.Application.addServers (/home/noor/stuffs/node_modules/pomelo/lib/application.js:873:14)
    at Handler.handler.queryEntry (/home/noor/stuffs/chatofpomelo-websocket/game-server/app/servers/gate/handler/gateHandler.js:23:11)
_

**Comment by fantasyni** [comment]
@nurulnabi you should just not directly call app.addServers, it is the internal api
