### ISSUE TITLE
TypeError: Cannot read property 'getByUid' of undefined

### ISSUE THREAD

**Issue by jsnoops** [NetEase/pomelo#911]
[2017-02-08 21:24:40.694] [ERROR] console -  Caught exception: TypeError: Cannot read property 'getByUid' of undefined

I'm getting this error when I try running channel.pushMessage(param) from a backend handler class. 

This is the script - 

```
module.exports = function(app) {
    return new Handler(app);
};

var Handler = function(app) {
    this.app = app;
    this.channelService = app.get('channelService');
};

var handler = Handler.prototype;

/**
 * Player enter scene, and response the related information such as
 * playerInfo, areaInfo and mapData to client.
 *
 * @param {Object} msg
 * @param {Object} session
 * @param {Function} next
 * @api public
 */
handler.enterScene = function(msg, session, next) {

    var match = session.match;

    newPlayer = {}
    newPlayer.id = session.uid
    newPlayer.serverId = this.app.get('serverId')

    console.log('the frontend id is ', session.frontendId)

    match.addPlayer(newPlayer);
    player = match.getPlayer(newPlayer.id);

    // now that we succesfully added the player to the match/channel we can send a spawn
    var param = {
        route: 'onSpawn',
        user: session.uid,
        x: player.components['PositionComponent'].x,
        y: player.components['PositionComponent'].y
    };

    var channel = this.channelService.getChannel(session.get('rid'), true);


    channel.pushMessage(param);



    console.log('the area is', session.match)
    next(null, {
        code: 200,
        data: 'it worked'
    });
};
```

And this is the whole error message

[2017-02-08 21:24:40.694] [ERROR] console -  Caught exception: TypeError: Cannot read property 'getByUid' of undefined
    at Remote.pushMessage (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/remote/frontend/channelRemote.js:38:30)
    at /home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/channelService.js:432:45
    at sendMessage (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/channelService.js:437:7)
    at sendMessageByGroup (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/channelService.js:444:7)
    at Channel.pushMessage (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/channelService.js:331:3)
    at Handler.handler.enterScene (/home/gotti/WebstormProjects/gunmo2/game-server/app/servers/match/handler/playerHandler.js:49:13)
    at Service.handle (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/handlerService.js:59:20)
    at handle (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/server/server.js:375:25)
    at next (/home/gotti/WebstormProjects/gunmo2/game-server/node_modules/pomelo/lib/common/service/filterService.js:50:7)
    at Filter.before (/home/gotti/WebstormProjects/gunmo2/game-server/app/servers/match/filter/playerFilter.js:18:5)

Does anyone know why it's doing this?

**Comment by Goman24431188** [comment]
I get the same problem after upgraded to the last pomelo version.

**Comment by isghost** [comment]
+1

**Comment by isghost** [comment]
I found the reason. channle.add API

    add
    Channel.prototype.add()
    type: method
    Params
    uid - user id
    sid - frontend server id which user has connected to
    dd user to channel.

sid must be a fronted server id. I used backend serverId, so I get this error.
