### ISSUE TITLE
Crash happend after update from 1.2.3

### ISSUE THREAD

**Issue by jifaxu** [NetEase/pomelo#924]
I update pomelo from 1.2.3 to 2.2.5, everything is ok until I perform pressure test on it, it crashed.

After read the logs, I think the crash is caused by mqtt rpc.

Anyone can help me? Thanks.

**Comment by fantasyni** [comment]
provide your crash logs please

**Comment by jifaxu** [comment]
The only useful log I can find :

rpc-connector-server-1.log
```
[2017-02-20 10:59:52.304] [ERROR] pomelo-rpc - rpc connector-server-1 callback timeout 30000, remote server 1406 host: 172.18.254.71, port: 3321
[2017-02-20 10:59:52.309] [ERROR] pomelo-rpc - [pomelo-rpc] fail to send message Error: rpc connector-server-1 callback timeout 30000, remote server 1406 host: 172.18.254.71, port: 3321
    at Timeout.<anonymous> (/Users/Jifa/workspace/node/game-js-slots-server/game-server/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/mqtt-mailbox.js:257:16)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
[2017-02-20 10:59:52.311] [ERROR] pomelo-rpc - rpc failed with error, remote server: slots-server-1, msg: {"namespace":"user","serverType":"slots","service":"entryRemote","method":"add","args":[{"uid":120275,"sid":"connector-server-1"}]}, error code: 5
[2017-02-20 10:59:52.312] [ERROR] pomelo-rpc - rpc connector-server-1 callback timeout 30000, remote server 1408 host: 172.18.254.71, port: 3321
[2017-02-20 10:59:52.313] [ERROR] pomelo-rpc - [pomelo-rpc] fail to send message Error: rpc connector-server-1 callback timeout 30000, remote server 1408 host: 172.18.254.71, port: 3321
    at Timeout.<anonymous> (/Users/Jifa/workspace/node/game-js-slots-server/game-server/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/mqtt-mailbox.js:257:16)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

```

**Comment by AdoBeatTheWorld** [comment]
这个看起来是连接超时吧，remote server 1406 host: 172.18.254.71, port: 3321这个服务器确定是状态是正常的么

**Comment by jifaxu** [comment]
就是这个服务器跑着跑着挂掉了，1.2.3  就没问题

**Comment by AdoBeatTheWorld** [comment]
一般会有本地log文件，可以看看log文件里面是怎么说的

**Comment by yorkyu** [comment]
有可能是你的业务服务器中handler函数没有处理回调.
你就看你首次出现这个错误前面的调用日志看是哪个协议包.

**Comment by cwk8866** [comment]
请问找到这个问题的解决办法了吗,我现在也遇到这个问题,有点莫名其妙,就其中一个服务器会报这个错误log

**Comment by xiaobear250** [comment]
这个问题我解决了。无论是客户端对服务器的notify，还是服务器前后端的rpc调用，都必须执行回调函数（next或者cb）。即使不需要也要弄个空函数进去。
