### ISSUE TITLE
[ERROR] pomelo-rpc - [mqtt-acceptor] process rpc message error TypeError: callback is not a function

### ISSUE THREAD

**Issue by ahmadsyamim** [NetEase/pomelo#970]
[2017-07-11 16:24:58.626] [INFO] console - [2017-07-11 16:24:58.623] [ERROR] pomelo-rpc - [mqtt-acceptor] process rpc message error TypeError: callback is not a function
    at Object.create (/Users/user/mmo/lordofpomelo/game-server/app/dao/mysql/dao-pool.js:18:4)
    at Pool._createResource (/Users/user/mmo/lordofpomelo/game-server/node_modules/generic-pool/lib/Pool.js:279:42)
    at Pool._dispense (/Users/user/mmo/lordofpomelo/game-server/node_modules/generic-pool/lib/Pool.js:210:12)
    at Pool.acquire (/Users/user/mmo/lordofpomelo/game-server/node_modules/generic-pool/lib/Pool.js:406:10)
    at Object.NND.query (/Users/user/mmo/lordofpomelo/game-server/app/dao/mysql/mysql.js:24:8)
    at Object.userDao.getUserById (/Users/user/mmo/lordofpomelo/game-server/app/dao/userDao.js:207:29)
    at Remote.pro.auth (/Users/user/mmo/lordofpomelo/game-server/app/servers/auth/remote/authRemote.js:40:10)
    at Dispatcher.pro.route (/Users/user/mmo/lordofpomelo/game-server/node_modules/pomelo-rpc/lib/rpc-server/dispatcher.js:52:10)
    at Acceptor.cb (/Users/user/mmo/lordofpomelo/game-server/node_modules/pomelo-rpc/lib/rpc-server/gateway.js:22:16)
    at processMsg (/Users/user/mmo/lordofpomelo/game-server/node_modules/pomelo-rpc/lib/rpc-server/acceptors/mqtt-acceptor.js:138:12)
[2017-07-11 16:24:58.630] [INFO] console - [2017-07-11 16:24:58.628] [WARN] pomelo-rpc - [mqtt-mailbox] timer is not exsits, serverId: connector-server-2 remote: undefined, host: 127.0.0.1, port: 3650
[2017-07-11 16:25:01.001] [ERROR] pomelo - [/Users/user/mmo/lordofpomelo/game-server/node_modules/pomelo/lib/filters/handler/timeout.js] request "connector.entryHandler.entry" timeout.
[2017-07-11 16:25:18.021] [INFO] console - [2017-07-11 16:25:18.021] [ERROR] pomelo-rpc - [mqtt-mailbox] rpc connector-server-2 callback timeout 20000, remote server 0 host: 127.0.0.1, port: 3650
[2017-07-11 16:25:18.026] [INFO] console - [2017-07-11 16:25:18.025] [ERROR] pomelo-rpc - [MailStation] [pomelo-rpc] fail to send message Error: rpc connector-server-2 callback timeout 20000, remote server 0 host: 127.0.0.1, port: 3650
    at Timeout.<anonymous> (/Users/user/mmo/lordofpomelo/game-server/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/mqtt-mailbox.js:257:16)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-07-11 16:25:18.027] [INFO] console - [2017-07-11 16:25:18.027] [ERROR] pomelo-rpc - [failprocess] rpc failed with error, remote server: auth-server-1, msg: {"namespace":"user","serverType":"auth","service":"authRemote","method":"auth","args":["b7234bc1efdc628b316fac8b3864097a"]}, error code: 5

**Comment by Balbo76** [comment]
me too

**Comment by Balbo76** [comment]
I was missing the number of arguments when calling rpc functions (i forgot session), now my game server is starting to work
